# Generated by Django 3.0.5 on 2020-05-07 17:39

from django.conf import settings
from django.db import migrations, models
import woocommerce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WoocommerceStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('description', models.CharField(max_length=300, verbose_name='Descrição')),
                ('icon', models.CharField(max_length=10, verbose_name='Ícone')),
                ('color', models.CharField(max_length=7, verbose_name='Cor')),
                ('logo', models.ImageField(null=True, upload_to=woocommerce.models.image_path, verbose_name='Logomarca')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('mobile', models.CharField(max_length=16, verbose_name='Celular')),
                ('wp_user', models.CharField(max_length=50, verbose_name='WP_USER')),
                ('wp_pass', models.CharField(max_length=100, verbose_name='WP_PASS')),
                ('db_name', models.CharField(max_length=50, unique=True, verbose_name='DB_NAME')),
                ('db_user', models.CharField(max_length=50, verbose_name='DB_USER')),
                ('db_pass', models.CharField(max_length=100, verbose_name='DP_PASS')),
                ('api_user_id', models.IntegerField(verbose_name='API_USER_ID')),
                ('api_description', models.CharField(max_length=50, verbose_name='API_DESCRIPTION')),
                ('api_permissions', models.CharField(max_length=15, verbose_name='API_PERMISSIONS')),
                ('api_consumer_key', models.CharField(max_length=100, verbose_name='API_CONSUMER_KEY')),
                ('api_consumer_secret', models.CharField(max_length=100, verbose_name='API_CONSUMER_SECRET')),
                ('api_truncate_key', models.CharField(max_length=20, verbose_name='API_TRUNCATE_KEY')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ManyToManyField(related_name='woocommerce', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loja',
                'verbose_name_plural': 'Lojas',
            },
        ),
    ]
