# Generated by Django 3.0.5 on 2020-05-07 21:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('woocommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WoocommerceStore',
            new_name='StoreWoo',
        ),
    ]
