# Generated by Django 3.0.5 on 2020-05-07 21:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('woocommerce', '0002_auto_20200507_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storewoo',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
